[package]
name = "gsearch"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1"
urlencoding = "2.0.0"

[lib]
name = "gsearch"
path = "src/lib.rs"